# install php-cli and remove the apt cache
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y php-cli \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /app

COPY --chown=www-data:www-data ./site/ .

CMD "php -S 0.0.0.0:8000 -t ./site/"