FROM gcc:latest

WORKDIR /app
COPY helloworld.cpp .
RUN g++ helloworld.cpp -o helloworld

FROM alpine:latest

COPY --from=0 /app/helloworld /helloworld

WORKDIR /
RUN chmod +x /helloworld && ls -l

CMD ["sh", "-c", "ls -l && cat ./helloworld && /helloworld"]